### PR TITLE
Apply double-slash patch

### PR DESCRIPTION
**Pull request by jarednova**
Fix for #12

### CODE REVIEW

**Comment by patrickbjohnson** [comment]
@jarednova thank you for pushing this! However looks like this double slash still exists.

**Comment by jarednova** [comment]
@patrickbjohnson well that's no good! When you say the problem still exists, is that based on running this repo? A composer distribution? A Timber distribution that includes it?

**Comment by patrickbjohnson** [comment]
@jarednova Hey. Sorry I didn't expand in my initial comment. I'm pulling in this lib via composer and looks like the version composer references still has the error. 

This may be a different issue altogether but also looks like within composer the only way to import is using the version: `"*"`

**Comment by jarednova** [comment]
Hmmmm, I tried running this in terminal and things seemed to work:

```
Jareds-MacBook-Air:routes_test jared$ composer require upstatement/routes 0.6
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.7.0): Loading from cache
  - Installing altorouter/altorouter (v1.2.0): Loading from cache
  - Installing upstatement/routes (0.6): Downloading (100%)         
Writing lock file
Generating autoload files
Jareds-MacBook-Air:routes_test jared$ 
```
can you post a version of the exact commands or Composer file you've got so I can see if I can replicate the error?

**Comment by n3storm** [comment]
Updated timber today which updated routes and everthing is OK

**Comment by jarednova** [comment]
Great! glad to hear that went through w/o a hitch @n3storm

**Pull request merged**
