### PR TITLE
Remove lines modifying undefined object

### PR DESCRIPTION
**Pull request by Daronspence**
See #22

### CODE REVIEW

**Comment by Daronspence** [comment]
Any update here?

**Comment by jarednova** [comment]
Sorry, it's been a _crazy_ month as you can guess. Adding to my list of this week to get this wrapped up!

**Comment by Daronspence** [comment]
No problem! Appreciate it! Looks like we're waiting on a vendor for another week at least so you've got time :)

**Comment by jarednova** [comment]
I've confirmed that these lines aren't functional. I tried to replicate the issue described in #14, but was able to load the expected view in each circumstance.

**Pull request merged**
